name: Deploy Node.js App to exCloud


on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy on exCloud
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: 210.79.129.5
          username: ubuntu
          key: ${{ secrets.EXCLOUD_SSH_KEY }}
          script: |
            cd /home/ubuntu/DevOPs
            git pull 
            npm install
            pm2 restart 0