name: Deploy Node.js App to exCloud


on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        run: |
          docker build -t jsdev8080/chaicode-node .
          docker push jsdev8080/chaicode-node

      - name: Deploy on exCloud
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: 210.79.129.5
          username: ubuntu
          key: ${{ secrets.EXCLOUD_SSH_KEY }}
          script: |
            #kill existing container
            docker rm -f $(docker ps -q --filter ancestor=jsdev8080/chaicode-node) || true

            #again pull the fresh image from docker hub
            docker pull jsdev8080/chaicode-node

            #run docker run -d -p 8000:8000 jsdev8080/chaicode-node
            docker run -d -p 8000:8000 jsdev8080/chaicode-node

            #clean up unused images
            docker image prune -f